
solon.app:
   name: demo-app
   licence: "/mXForLnZZhRtfSkzBkezK0PCGdFl9VPX3V65uOXvhFCxv9pwuuLJdCVbr5Ji3xTaMNx/AVSGLJn55ZmaYU/73iiy4gLn+a9TdmELwLXr7pcI9LGRDTIqxvSANeBrfiywG8WD1I2S2ycVcSPy8cDr/jHHsXqXo1YBh8DLUNNpZ5ZUvjebBC34VQfK7QhhQMWKiNFs9dC/ADV5IyrpzaqjUoOoCzbJlBx9NOMj1Ym+CPONbHgN3v/oNO1HAp/a9MPdsgzgqJCSrS2Vt9HBDLhhzHKD3rf+8e8Y3jO1ssaQsI="
