
solon.app:
 name: demo-app
 licence: "Horutp18+elrUS7bfKFwGtHbV9uSj5mr4ILDe6Rnkexz312KBS7gfI+zw6Wtec6y3PdLex1jUk3UwSE3zZPAyn8oYhPdxzWcIhiYBxvENCFnuf2uXKQ+u8f3dpKQmo6/vfzpmW/1e7cCqlXJ1zyNTXGLkEXgVp3cE+eFfuUaUNAOSws8zY51Z4qqSvRj40c0w1Sfu4i8J51Vra2qyBgMww=="
