
solon.app:
 name: demo-app
 licence: "xFpS8KNW8H5UzJlSIewiF4t7S5qpoQta7p0SyTnOoq/lj8Hy8r2outvSF6dcNAKiqyrl5/7o4OM6k9uCFDzmge+zOvyqvWLTi0VR/db3muZQoKDaVaoyF/g1uAWntG4Aq1gjh8XcR52+kv8dHuv9xg0HqMU+XfSUUXFSvhwQOGlAq8MyyZxl3I28ymbgCKL1DSNj9cDEC2rCxG+TRHSvbg=="
