
solon.app:
 name: demo-app
 licence: "Q8rvvaj+T6dQ0t+xeh+aQwba/A/a2XF+st7fhhFOUrGxaW4P7SlusdE6sERLJ2h+JHFZ6ApUy3OxQ9l0I8UmBGE3/HUenpXel3q4Sfc0MQOg9N/wbvoEIMXBXrG6rXwbuO0ZQPjegD8ndruqG9wQ2/7uWJLRHmbuSMcIk06VBO2uuWdOzRyGRL9IAMrB+7X9BdEdCTbK1T7gvLzESZDikw=="
