
solon.app:
 name: demo-app
 licence: "ITO4R6kCM2aFUxZA1Hqne4NLZvQ7dJJPuzXjy/VbON/ltBbWATXdxKjRkn/fZ1vI8+PNqliC+xAjw0hLVrx/TsuMoNfPjRqTkBeTlx/l6JolG6tKX4GTNbXZ9pC+CYQLMXeJ3VywVBcTr6Qvu1D0fYJAIQigcLVHvSXy00KC3AHy97wKbl3wW3mwuY06uvACw1Sfu4i8J51Vra2qyBgMww=="
